const { MigrationInterface, QueryRunner } = require("typeorm");

module.exports = class test1643651811887 {
    name = 'test1643651811887'

    async up(queryRunner) {
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`instagram\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`neighborhoodIdNeighborhoodId\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`place_id\` \`place_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`place_id\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`signature\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`subCategoryId2SubCategoryId\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`subCategoryId3SubCategoryId\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`subCategoryIdSubCategoryId\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`userIdUserId\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`website\``);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`place_id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`signature\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`phone\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`website\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`instagram\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`subCategoryIdSubCategoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`subCategoryId2SubCategoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`subCategoryId3SubCategoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`neighborhoodIdNeighborhoodId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`userIdUserId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`id\` \`place_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD PRIMARY KEY (\`place_id\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`place_id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`time\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`category\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`image\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`userUserId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`category_id\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`category_id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`category\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`category\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`admin\` \`admin\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`title\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`description\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`isFavorite\``);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`isFavorite\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`approved\``);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`approved\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`city_id\``);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`city_id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`city\``);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`city\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`image_id\``);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`image_id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`image\``);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`image\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`image_owner\``);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`image_owner\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`place_id\``);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`place_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`neighborhoods\` DROP COLUMN \`neighborhood_id\``);
        await queryRunner.query(`ALTER TABLE \`neighborhoods\` ADD \`neighborhood_id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`neighborhoods\` DROP COLUMN \`neighborhood\``);
        await queryRunner.query(`ALTER TABLE \`neighborhoods\` ADD \`neighborhood\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`neighborhoods\` CHANGE \`city_id\` \`city_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD CONSTRAINT \`FK_08d9403cef8ea06878067ddfa1e\` FOREIGN KEY (\`subCategoryIdSubCategoryId\`) REFERENCES \`sub_category\`(\`sub_category_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD CONSTRAINT \`FK_6102a5264b92707fd07cde41ee9\` FOREIGN KEY (\`subCategoryId2SubCategoryId\`) REFERENCES \`sub_category\`(\`sub_category_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD CONSTRAINT \`FK_55a3305ada82fe2007cebe9ebb8\` FOREIGN KEY (\`subCategoryId3SubCategoryId\`) REFERENCES \`sub_category\`(\`sub_category_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD CONSTRAINT \`FK_6f1aaa7d2cad8742a2975ff34ea\` FOREIGN KEY (\`neighborhoodIdNeighborhoodId\`) REFERENCES \`neighborhood\`(\`neighborhood_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD CONSTRAINT \`FK_9159e49ca216a184de85129d803\` FOREIGN KEY (\`userIdUserId\`) REFERENCES \`user\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`sub_category\` ADD CONSTRAINT \`FK_b3dd2d9aa93fbc5635c32425a5c\` FOREIGN KEY (\`categoryIdCategoryId\`) REFERENCES \`category\`(\`category_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD CONSTRAINT \`FK_7f577535bf963c748d5d49139b8\` FOREIGN KEY (\`userUserId\`) REFERENCES \`user\`(\`user_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    async down(queryRunner) {
        await queryRunner.query(`ALTER TABLE \`place\` DROP FOREIGN KEY \`FK_7f577535bf963c748d5d49139b8\``);
        await queryRunner.query(`ALTER TABLE \`sub_category\` DROP FOREIGN KEY \`FK_b3dd2d9aa93fbc5635c32425a5c\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP FOREIGN KEY \`FK_9159e49ca216a184de85129d803\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP FOREIGN KEY \`FK_6f1aaa7d2cad8742a2975ff34ea\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP FOREIGN KEY \`FK_55a3305ada82fe2007cebe9ebb8\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP FOREIGN KEY \`FK_6102a5264b92707fd07cde41ee9\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP FOREIGN KEY \`FK_08d9403cef8ea06878067ddfa1e\``);
        await queryRunner.query(`ALTER TABLE \`neighborhoods\` CHANGE \`city_id\` \`city_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`neighborhoods\` DROP COLUMN \`neighborhood\``);
        await queryRunner.query(`ALTER TABLE \`neighborhoods\` ADD \`neighborhood\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`neighborhoods\` DROP COLUMN \`neighborhood_id\``);
        await queryRunner.query(`ALTER TABLE \`neighborhoods\` ADD \`neighborhood_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`place_id\``);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`place_id\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`image_owner\``);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`image_owner\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`image\``);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`image\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`image_id\``);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`image_id\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`city\``);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`city\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`city_id\``);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`city_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`approved\``);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`approved\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`isFavorite\``);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`isFavorite\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`description\``);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`description\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`title\``);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`title\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`admin\` \`admin\` tinyint NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`category\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`category\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`categories\` DROP COLUMN \`category_id\``);
        await queryRunner.query(`ALTER TABLE \`categories\` ADD \`category_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`userUserId\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`image\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`category\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`time\``);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`id\` \`place_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD PRIMARY KEY (\`place_id\`)`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`place_id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`userIdUserId\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`neighborhoodIdNeighborhoodId\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`subCategoryId3SubCategoryId\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`subCategoryId2SubCategoryId\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`subCategoryIdSubCategoryId\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`instagram\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`website\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`phone\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`signature\``);
        await queryRunner.query(`ALTER TABLE \`place\` DROP COLUMN \`place_id\``);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`website\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`userIdUserId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`subCategoryIdSubCategoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`subCategoryId3SubCategoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`subCategoryId2SubCategoryId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`signature\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`place_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD PRIMARY KEY (\`place_id\`)`);
        await queryRunner.query(`ALTER TABLE \`place\` CHANGE \`place_id\` \`place_id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`phone\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`neighborhoodIdNeighborhoodId\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`place\` ADD \`instagram\` varchar(255) NOT NULL`);
    }
}
