

POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email": "kall@com",
    "password": "12345"
}


GET http://localhost:3000/places/places
Content-Type: application/json


GET http://localhost:3000/users/colors/green
Content-Type: application/json


GET http://localhost:3000/users/colors
Content-Type: application/json